# Generated by Django 2.0.6 on 2018-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=24, unique=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], default='EN', max_length=2)),
            ],
        ),
    ]
