# Generated by Django 2.0.6 on 2018-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.AddField(
            model_name='userlang',
            name='files',
            field=models.ManyToManyField(to='fb_bot.File'),
        ),
    ]
